AllCops:
  Exclude:
    - 'why/**/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'db/seeds.rb'
    - 'db/seeds/*'
    - 'vendor/**/*'
    - 'app/controllers/checkout_controller.rb'
    - 'app/models/reservation.rb'
StringLiterals:
  Enabled: false
AlignParameters:
  Enabled: false