  version: '2'

  services:
    app:
      build: .
      command: bundle exec puma -p 3000
      environment:
        BUNDLE_JOBS: 8
        BUNDLE_PATH: /bundle
        POSTGRES_USER: postgres
      depends_on:
        - db
      ports:
        - '3000:3000'
      volumes:
        - .:/app
        - bundle-data:/bundle
    db:
      image: postgres
      volumes:
        - db-data:/var/lib/postgresql/data
  volumes:
    db-data:
      driver: local
    bundle-data:
      driver: local
