  version: '2'

  services:
    app:
      build: .
      image: marketmymarket/ti_storage
      command: bundle exec puma -p 3000
      environment:
        BUNDLE_JOBS: 8
        BUNDLE_PATH: /bundle
        POSTGRES_USER: postgres
      depends_on:
        - db
      ports:
        - '3000:3000'
      volumes:
        - .:/app
      volumes_from:
        - bundle
    db:
      image: postgres
      volumes:
        - db-data:/var/lib/postgresql/data
    bundle:
      image: busybox
      volumes:
        - /bundle
  volumes:
    db-data:
      driver: local
