default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres

development:
  <<: *default
  database: ti_storage_development

test:
  <<: *default
  database: ti_storage_test

production:
  <<: *default
  database: ti_storage_production
  username: ti_storage
  password: <%= ENV['DATABASE_PASSWORD'] %>

ci:
  <<: *default
  database: circle_ruby_test
  host: localhost
  username: ubuntu
